# Generated by Django 2.2.5 on 2019-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Varsity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('varsitycategory', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=200)),
                ('established', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('newsandevent', models.TextField(max_length=200)),
                ('admissioninfo', models.TextField(max_length=500)),
            ],
        ),
    ]
