# Generated by Django 2.2.5 on 2019-09-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnextapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departmenttype', models.IntegerField()),
                ('varsity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsnextapp.Varsity')),
            ],
        ),
    ]
