# Generated by Django 2.2.5 on 2019-09-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnextapp', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='varsity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='whatsnextapp.Varsity'),
        ),
    ]
