# Generated by Django 2.2.5 on 2019-09-06 20:18

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import whatsnextapp.enums


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnextapp', '0003_auto_20190906_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirementtype', django_enumfield.db.fields.EnumField(default=0, enum=whatsnextapp.enums.RequirementType)),
                ('Value', models.CharField(max_length=200)),
                ('level', django_enumfield.db.fields.EnumField(default=1, enum=whatsnextapp.enums.RequirementLevel)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('semesters', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('degreelevel', django_enumfield.db.fields.EnumField(default=0, enum=whatsnextapp.enums.DegreeLevel)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', django_enumfield.db.fields.EnumField(default=1, enum=whatsnextapp.enums.SchoolLevel)),
                ('discipline', django_enumfield.db.fields.EnumField(default=0, enum=whatsnextapp.enums.Discipline)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='departmenttype',
            field=django_enumfield.db.fields.EnumField(default=0, enum=whatsnextapp.enums.DepartmentCategory),
        ),
        migrations.AlterField(
            model_name='varsity',
            name='varsitycategory',
            field=django_enumfield.db.fields.EnumField(default=0, enum=whatsnextapp.enums.VarsityCategory),
        ),
        migrations.CreateModel(
            name='RequirementSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionrequirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirementsubjects', to='whatsnextapp.AdmissionRequirement')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectrequirements', to='whatsnextapp.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionrequirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirementdegrees', to='whatsnextapp.AdmissionRequirement')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissionrequirements', to='whatsnextapp.Degree')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='whatsnextapp.Department'),
        ),
        migrations.AddField(
            model_name='degree',
            name='varsity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='whatsnextapp.Varsity'),
        ),
    ]
