# Generated by Django 2.2.5 on 2019-09-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnextapp', '0004_auto_20190907_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varsity',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
