# Generated by Django 2.2.5 on 2019-09-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnextapp', '0005_auto_20190907_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varsity',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
